version: "3.9"

services:
  db:
    container_name: database
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
     - '5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
    #   - ./.env.dev

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    # networks:
    #   - app-network

    # volumes:
    #   - ./conf/nginx.conf:/etc/nginx/nginx.conf

  elasticsearch:
    image: elasticsearch:6.5.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    # networks:
    #   - docker_elk
